"""add profit_loss_net and profit_rate_net to order_histories

Revision ID: 0b2cdcfca762
Revises: d214602eb60b
Create Date: 2026-03-23 11:38:31.700749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2cdcfca762'
down_revision: Union[str, Sequence[str], None] = 'd214602eb60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_histories', sa.Column('profit_loss_net', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('order_histories', sa.Column('profit_rate_net', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_histories', 'profit_rate_net')
    op.drop_column('order_histories', 'profit_loss_net')
    # ### end Alembic commands ###
