"""update decision and order history fields

Revision ID: 315f814d5e29
Revises: 3385e5c2ee77
Create Date: 2026-03-20 20:15:14.773050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '315f814d5e29'
down_revision: Union[str, Sequence[str], None] = '3385e5c2ee77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision_histories', sa.Column('processing_time_ms', sa.Integer(), nullable=False))
    op.alter_column('decision_histories', 'decision',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('decision_histories', 'request_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('decision_histories', 'response_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('ix_decision_histories_decision', 'decision_histories', ['decision'], unique=False)
    op.create_index('ix_decision_histories_is_error_created_at', 'decision_histories', ['is_error', 'created_at'], unique=False)
    op.add_column('order_histories', sa.Column('order_quantity', sa.Integer(), nullable=False))
    op.add_column('order_histories', sa.Column('order_total_amount', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('order_histories', sa.Column('result_price', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('order_histories', sa.Column('result_quantity', sa.Integer(), nullable=False))
    op.add_column('order_histories', sa.Column('result_total_amount', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('order_histories', sa.Column('order_placed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('order_histories', sa.Column('result_executed_at', sa.DateTime(), nullable=True))
    op.alter_column('order_histories', 'decision_history_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_histories', 'stock_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('order_histories', 'order_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=False)
    op.alter_column('order_histories', 'profit_loss',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.create_index('ix_order_histories_order_placed_at', 'order_histories', ['order_placed_at'], unique=False)
    op.create_index('ix_order_histories_result_executed_at', 'order_histories', ['result_executed_at'], unique=False)
    op.create_index('ix_order_histories_stock_code', 'order_histories', ['stock_code'], unique=False)
    op.create_index('ix_order_histories_stock_code_created_at', 'order_histories', ['stock_code', 'created_at'], unique=False)
    op.drop_constraint(op.f('order_histories_decision_history_id_fkey'), 'order_histories', type_='foreignkey')
    op.create_foreign_key(None, 'order_histories', 'decision_histories', ['decision_history_id'], ['id'], ondelete='CASCADE')
    op.drop_column('order_histories', 'quantity')
    op.drop_column('order_histories', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_histories', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('order_histories', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_histories', type_='foreignkey')
    op.create_foreign_key(op.f('order_histories_decision_history_id_fkey'), 'order_histories', 'decision_histories', ['decision_history_id'], ['id'])
    op.drop_index('ix_order_histories_stock_code_created_at', table_name='order_histories')
    op.drop_index('ix_order_histories_stock_code', table_name='order_histories')
    op.drop_index('ix_order_histories_result_executed_at', table_name='order_histories')
    op.drop_index('ix_order_histories_order_placed_at', table_name='order_histories')
    op.alter_column('order_histories', 'profit_loss',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('order_histories', 'order_price',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('order_histories', 'stock_code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.alter_column('order_histories', 'decision_history_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('order_histories', 'result_executed_at')
    op.drop_column('order_histories', 'order_placed_at')
    op.drop_column('order_histories', 'result_total_amount')
    op.drop_column('order_histories', 'result_quantity')
    op.drop_column('order_histories', 'result_price')
    op.drop_column('order_histories', 'order_total_amount')
    op.drop_column('order_histories', 'order_quantity')
    op.drop_index('ix_decision_histories_is_error_created_at', table_name='decision_histories')
    op.drop_index('ix_decision_histories_decision', table_name='decision_histories')
    op.alter_column('decision_histories', 'response_payload',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('decision_histories', 'request_payload',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('decision_histories', 'decision',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('decision_histories', 'processing_time_ms')
    # ### end Alembic commands ###
