"""initial models

Revision ID: 3385e5c2ee77
Revises: 
Create Date: 2026-03-20 20:01:46.302689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3385e5c2ee77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=True),
    sa.Column('stock_name', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_buy_price', sa.Float(), nullable=False),
    sa.Column('cash_amount', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dart_disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rcept_no', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dart_disclosures_stock_code'), 'dart_disclosures', ['stock_code'], unique=False)
    op.create_table('decision_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('parsed_decision', sa.JSON(), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_histories_created_at'), 'decision_histories', ['created_at'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('change_rate', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('per', sa.Float(), nullable=True),
    sa.Column('pbr', sa.Float(), nullable=True),
    sa.Column('high_52w', sa.Float(), nullable=True),
    sa.Column('low_52w', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_stock_code'), 'market_snapshots', ['stock_code'], unique=False)
    op.create_table('minute_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_minute_candles_datetime', 'minute_candles', ['datetime'], unique=False)
    op.create_index('ix_minute_candles_stock_code', 'minute_candles', ['stock_code'], unique=False)
    op.create_index('ix_minute_candles_stock_code_datetime', 'minute_candles', ['stock_code', 'datetime'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('useful', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_stock_code'), 'news', ['stock_code'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('target_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=False),
    sa.Column('dart_corp_code', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code')
    )
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_history_id', sa.Integer(), nullable=True),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('stock_name', sa.String(length=50), nullable=False),
    sa.Column('order_type', sa.String(length=4), nullable=False),
    sa.Column('order_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('profit_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_history_id'], ['decision_histories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_histories_created_at'), 'order_histories', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_histories_created_at'), table_name='order_histories')
    op.drop_table('order_histories')
    op.drop_table('todos')
    op.drop_table('target_stocks')
    op.drop_table('system_parameters')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_news_stock_code'), table_name='news')
    op.drop_table('news')
    op.drop_index('ix_minute_candles_stock_code_datetime', table_name='minute_candles')
    op.drop_index('ix_minute_candles_stock_code', table_name='minute_candles')
    op.drop_index('ix_minute_candles_datetime', table_name='minute_candles')
    op.drop_table('minute_candles')
    op.drop_index(op.f('ix_market_snapshots_stock_code'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_decision_histories_created_at'), table_name='decision_histories')
    op.drop_table('decision_histories')
    op.drop_index(op.f('ix_dart_disclosures_stock_code'), table_name='dart_disclosures')
    op.drop_table('dart_disclosures')
    op.drop_table('assets')
    # ### end Alembic commands ###
