"""add buy_order_id to order_histories

Revision ID: 4eb5eec722cd
Revises: 237217dabbbb
Create Date: 2026-03-25 09:18:25.383134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb5eec722cd'
down_revision: Union[str, Sequence[str], None] = '237217dabbbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_histories', sa.Column('buy_order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_histories', 'order_histories', ['buy_order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_histories', type_='foreignkey')
    op.drop_column('order_histories', 'buy_order_id')
    # ### end Alembic commands ###
