"""add orderbook_snapshots table

Revision ID: bc5cbf66d29a
Revises: 4eb5eec722cd
Create Date: 2026-03-26 16:11:07.364975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5cbf66d29a'
down_revision: Union[str, Sequence[str], None] = '4eb5eec722cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('ask_price1', sa.Integer(), nullable=False),
    sa.Column('ask_price2', sa.Integer(), nullable=False),
    sa.Column('ask_price3', sa.Integer(), nullable=False),
    sa.Column('ask_price4', sa.Integer(), nullable=False),
    sa.Column('ask_price5', sa.Integer(), nullable=False),
    sa.Column('ask_volume1', sa.BigInteger(), nullable=False),
    sa.Column('ask_volume2', sa.BigInteger(), nullable=False),
    sa.Column('ask_volume3', sa.BigInteger(), nullable=False),
    sa.Column('ask_volume4', sa.BigInteger(), nullable=False),
    sa.Column('ask_volume5', sa.BigInteger(), nullable=False),
    sa.Column('bid_price1', sa.Integer(), nullable=False),
    sa.Column('bid_price2', sa.Integer(), nullable=False),
    sa.Column('bid_price3', sa.Integer(), nullable=False),
    sa.Column('bid_price4', sa.Integer(), nullable=False),
    sa.Column('bid_price5', sa.Integer(), nullable=False),
    sa.Column('bid_volume1', sa.BigInteger(), nullable=False),
    sa.Column('bid_volume2', sa.BigInteger(), nullable=False),
    sa.Column('bid_volume3', sa.BigInteger(), nullable=False),
    sa.Column('bid_volume4', sa.BigInteger(), nullable=False),
    sa.Column('bid_volume5', sa.BigInteger(), nullable=False),
    sa.Column('total_ask_volume', sa.BigInteger(), nullable=True),
    sa.Column('total_bid_volume', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'snapshot_at', name='uq_orderbook_snapshots_stock_code_snapshot_at')
    )
    op.create_index('ix_orderbook_snapshots_snapshot_at', 'orderbook_snapshots', ['snapshot_at'], unique=False)
    op.create_index('ix_orderbook_snapshots_stock_code', 'orderbook_snapshots', ['stock_code'], unique=False)
    op.create_index('ix_orderbook_snapshots_stock_code_snapshot_at', 'orderbook_snapshots', ['stock_code', 'snapshot_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orderbook_snapshots_stock_code_snapshot_at', table_name='orderbook_snapshots')
    op.drop_index('ix_orderbook_snapshots_stock_code', table_name='orderbook_snapshots')
    op.drop_index('ix_orderbook_snapshots_snapshot_at', table_name='orderbook_snapshots')
    op.drop_table('orderbook_snapshots')
    # ### end Alembic commands ###
