"""sync models with django originals

Revision ID: d214602eb60b
Revises: 315f814d5e29
Create Date: 2026-03-20 20:18:09.909623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd214602eb60b'
down_revision: Union[str, Sequence[str], None] = '315f814d5e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('unit_price', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('assets', sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('assets', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('assets', 'stock_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.create_index('ix_assets_stock_code', 'assets', ['stock_code'], unique=False)
    op.create_index('ix_assets_stock_code_updated_at', 'assets', ['stock_code', 'updated_at'], unique=False)
    op.drop_column('assets', 'cash_amount')
    op.drop_column('assets', 'avg_buy_price')
    op.add_column('dart_disclosures', sa.Column('external_id', sa.String(length=128), nullable=False))
    op.add_column('dart_disclosures', sa.Column('corp_code', sa.String(length=64), nullable=False))
    op.add_column('dart_disclosures', sa.Column('link', sa.String(length=2048), nullable=False))
    op.alter_column('dart_disclosures', 'stock_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('dart_disclosures', 'stock_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('dart_disclosures', 'rcept_no',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('dart_disclosures', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('dart_disclosures', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('ix_dart_disclosures_corp_code', 'dart_disclosures', ['corp_code'], unique=False)
    op.create_index('ix_dart_disclosures_created_at', 'dart_disclosures', ['created_at'], unique=False)
    op.create_index('ix_dart_disclosures_published_at', 'dart_disclosures', ['published_at'], unique=False)
    op.create_index('ix_dart_disclosures_stock_code_created_at', 'dart_disclosures', ['stock_code', 'created_at'], unique=False)
    op.create_index('ix_dart_disclosures_stock_code_published_at', 'dart_disclosures', ['stock_code', 'published_at'], unique=False)
    op.create_unique_constraint(None, 'dart_disclosures', ['external_id'])
    op.drop_column('dart_disclosures', 'url')
    op.add_column('market_snapshots', sa.Column('external_id', sa.String(length=128), nullable=False))
    op.add_column('market_snapshots', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('market_snapshots', sa.Column('eps', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('market_snapshots', sa.Column('bps', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('market_snapshots', sa.Column('stac_month', sa.String(length=64), nullable=False))
    op.add_column('market_snapshots', sa.Column('lstn_stcn', sa.String(length=128), nullable=False))
    op.add_column('market_snapshots', sa.Column('hts_avls', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('cpfn', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('market_snapshots', sa.Column('stck_fcam', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('w52_hgpr', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('w52_hgpr_date', sa.Date(), nullable=True))
    op.add_column('market_snapshots', sa.Column('w52_hgpr_vrss_prpr_ctrt', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('market_snapshots', sa.Column('w52_lwpr', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('w52_lwpr_date', sa.Date(), nullable=True))
    op.add_column('market_snapshots', sa.Column('w52_lwpr_vrss_prpr_ctrt', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('market_snapshots', sa.Column('d250_hgpr', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('d250_hgpr_date', sa.Date(), nullable=True))
    op.add_column('market_snapshots', sa.Column('d250_hgpr_vrss_prpr_rate', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('market_snapshots', sa.Column('d250_lwpr', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('d250_lwpr_date', sa.Date(), nullable=True))
    op.add_column('market_snapshots', sa.Column('d250_lwpr_vrss_prpr_rate', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('market_snapshots', sa.Column('stck_dryy_hgpr', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('dryy_hgpr_date', sa.Date(), nullable=True))
    op.add_column('market_snapshots', sa.Column('dryy_hgpr_vrss_prpr_rate', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('market_snapshots', sa.Column('stck_dryy_lwpr', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('dryy_lwpr_date', sa.Date(), nullable=True))
    op.add_column('market_snapshots', sa.Column('dryy_lwpr_vrss_prpr_rate', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('market_snapshots', sa.Column('hts_frgn_ehrt', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('market_snapshots', sa.Column('frgn_hldn_qty', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('frgn_ntby_qty', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('pgtr_ntby_qty', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('vol_tnrt', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('market_snapshots', sa.Column('whol_loan_rmnd_rate', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('market_snapshots', sa.Column('marg_rate', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('market_snapshots', sa.Column('crdt_able_yn', sa.String(length=2), nullable=False))
    op.add_column('market_snapshots', sa.Column('ssts_yn', sa.String(length=2), nullable=False))
    op.add_column('market_snapshots', sa.Column('iscd_stat_cls_code', sa.String(length=16), nullable=False))
    op.add_column('market_snapshots', sa.Column('mrkt_warn_cls_code', sa.String(length=16), nullable=False))
    op.add_column('market_snapshots', sa.Column('invt_caful_yn', sa.String(length=2), nullable=False))
    op.add_column('market_snapshots', sa.Column('short_over_yn', sa.String(length=2), nullable=False))
    op.add_column('market_snapshots', sa.Column('sltr_yn', sa.String(length=2), nullable=False))
    op.add_column('market_snapshots', sa.Column('mang_issu_cls_code', sa.String(length=16), nullable=False))
    op.add_column('market_snapshots', sa.Column('temp_stop_yn', sa.String(length=2), nullable=False))
    op.add_column('market_snapshots', sa.Column('oprc_rang_cont_yn', sa.String(length=2), nullable=False))
    op.add_column('market_snapshots', sa.Column('clpr_rang_cont_yn', sa.String(length=2), nullable=False))
    op.add_column('market_snapshots', sa.Column('grmn_rate_cls_code', sa.String(length=16), nullable=False))
    op.add_column('market_snapshots', sa.Column('new_hgpr_lwpr_cls_code', sa.String(length=16), nullable=False))
    op.add_column('market_snapshots', sa.Column('rprs_mrkt_kor_name', sa.String(length=128), nullable=False))
    op.add_column('market_snapshots', sa.Column('bstp_kor_isnm', sa.String(length=128), nullable=False))
    op.add_column('market_snapshots', sa.Column('vi_cls_code', sa.String(length=16), nullable=False))
    op.add_column('market_snapshots', sa.Column('ovtm_vi_cls_code', sa.String(length=16), nullable=False))
    op.add_column('market_snapshots', sa.Column('last_ssts_cntg_qty', sa.Integer(), nullable=True))
    op.add_column('market_snapshots', sa.Column('apprch_rate', sa.Numeric(precision=20, scale=6), nullable=True))
    op.alter_column('market_snapshots', 'stock_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('market_snapshots', 'stock_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('market_snapshots', 'per',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.alter_column('market_snapshots', 'pbr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=6),
               existing_nullable=True)
    op.create_index('ix_market_snapshots_created_at', 'market_snapshots', ['created_at'], unique=False)
    op.create_index('ix_market_snapshots_published_at', 'market_snapshots', ['published_at'], unique=False)
    op.create_index('ix_market_snapshots_stock_code_created_at', 'market_snapshots', ['stock_code', 'created_at'], unique=False)
    op.create_index('ix_market_snapshots_stock_code_published_at', 'market_snapshots', ['stock_code', 'published_at'], unique=False)
    op.create_unique_constraint(None, 'market_snapshots', ['external_id'])
    op.drop_column('market_snapshots', 'high_52w')
    op.drop_column('market_snapshots', 'volume')
    op.drop_column('market_snapshots', 'change_rate')
    op.drop_column('market_snapshots', 'market_cap')
    op.drop_column('market_snapshots', 'current_price')
    op.drop_column('market_snapshots', 'low_52w')
    op.add_column('minute_candles', sa.Column('minute_at', sa.DateTime(), nullable=False))
    op.alter_column('minute_candles', 'open',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('minute_candles', 'high',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('minute_candles', 'low',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('minute_candles', 'close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_minute_candles_datetime'), table_name='minute_candles')
    op.drop_index(op.f('ix_minute_candles_stock_code_datetime'), table_name='minute_candles')
    op.create_index('ix_minute_candles_minute_at', 'minute_candles', ['minute_at'], unique=False)
    op.create_index('ix_minute_candles_stock_code_minute_at', 'minute_candles', ['stock_code', 'minute_at'], unique=False)
    op.create_unique_constraint('uq_minute_candles_stock_code_minute_at', 'minute_candles', ['stock_code', 'minute_at'])
    op.drop_column('minute_candles', 'datetime')
    op.drop_column('minute_candles', 'created_at')
    op.add_column('news', sa.Column('external_id', sa.String(length=128), nullable=False))
    op.add_column('news', sa.Column('link', sa.String(length=2048), nullable=False))
    op.add_column('news', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('news', 'stock_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('news', 'stock_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('news', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('news', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('ix_news_created_at', 'news', ['created_at'], unique=False)
    op.create_index('ix_news_published_at', 'news', ['published_at'], unique=False)
    op.create_index('ix_news_stock_code_created_at', 'news', ['stock_code', 'created_at'], unique=False)
    op.create_index('ix_news_stock_code_published_at', 'news', ['stock_code', 'published_at'], unique=False)
    op.create_index('ix_news_stock_code_useful_created_at', 'news', ['stock_code', 'useful', 'created_at'], unique=False)
    op.create_unique_constraint(None, 'news', ['external_id'])
    op.drop_column('news', 'url')
    op.add_column('todos', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('todos', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('todos', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_todos_status'), 'todos', ['status'], unique=False)
    op.drop_column('todos', 'is_done')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_done', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_todos_status'), table_name='todos')
    op.alter_column('todos', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('todos', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('todos', 'status')
    op.add_column('news', sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_index('ix_news_stock_code_useful_created_at', table_name='news')
    op.drop_index('ix_news_stock_code_published_at', table_name='news')
    op.drop_index('ix_news_stock_code_created_at', table_name='news')
    op.drop_index('ix_news_published_at', table_name='news')
    op.drop_index('ix_news_created_at', table_name='news')
    op.alter_column('news', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('news', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('news', 'stock_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('news', 'stock_code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.drop_column('news', 'description')
    op.drop_column('news', 'link')
    op.drop_column('news', 'external_id')
    op.add_column('minute_candles', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('minute_candles', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_minute_candles_stock_code_minute_at', 'minute_candles', type_='unique')
    op.drop_index('ix_minute_candles_stock_code_minute_at', table_name='minute_candles')
    op.drop_index('ix_minute_candles_minute_at', table_name='minute_candles')
    op.create_index(op.f('ix_minute_candles_stock_code_datetime'), 'minute_candles', ['stock_code', 'datetime'], unique=False)
    op.create_index(op.f('ix_minute_candles_datetime'), 'minute_candles', ['datetime'], unique=False)
    op.alter_column('minute_candles', 'close',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('minute_candles', 'low',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('minute_candles', 'high',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('minute_candles', 'open',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('minute_candles', 'minute_at')
    op.add_column('market_snapshots', sa.Column('low_52w', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('market_snapshots', sa.Column('market_cap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('change_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('market_snapshots', sa.Column('high_52w', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'market_snapshots', type_='unique')
    op.drop_index('ix_market_snapshots_stock_code_published_at', table_name='market_snapshots')
    op.drop_index('ix_market_snapshots_stock_code_created_at', table_name='market_snapshots')
    op.drop_index('ix_market_snapshots_published_at', table_name='market_snapshots')
    op.drop_index('ix_market_snapshots_created_at', table_name='market_snapshots')
    op.alter_column('market_snapshots', 'pbr',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('market_snapshots', 'per',
               existing_type=sa.Numeric(precision=20, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('market_snapshots', 'stock_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('market_snapshots', 'stock_code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.drop_column('market_snapshots', 'apprch_rate')
    op.drop_column('market_snapshots', 'last_ssts_cntg_qty')
    op.drop_column('market_snapshots', 'ovtm_vi_cls_code')
    op.drop_column('market_snapshots', 'vi_cls_code')
    op.drop_column('market_snapshots', 'bstp_kor_isnm')
    op.drop_column('market_snapshots', 'rprs_mrkt_kor_name')
    op.drop_column('market_snapshots', 'new_hgpr_lwpr_cls_code')
    op.drop_column('market_snapshots', 'grmn_rate_cls_code')
    op.drop_column('market_snapshots', 'clpr_rang_cont_yn')
    op.drop_column('market_snapshots', 'oprc_rang_cont_yn')
    op.drop_column('market_snapshots', 'temp_stop_yn')
    op.drop_column('market_snapshots', 'mang_issu_cls_code')
    op.drop_column('market_snapshots', 'sltr_yn')
    op.drop_column('market_snapshots', 'short_over_yn')
    op.drop_column('market_snapshots', 'invt_caful_yn')
    op.drop_column('market_snapshots', 'mrkt_warn_cls_code')
    op.drop_column('market_snapshots', 'iscd_stat_cls_code')
    op.drop_column('market_snapshots', 'ssts_yn')
    op.drop_column('market_snapshots', 'crdt_able_yn')
    op.drop_column('market_snapshots', 'marg_rate')
    op.drop_column('market_snapshots', 'whol_loan_rmnd_rate')
    op.drop_column('market_snapshots', 'vol_tnrt')
    op.drop_column('market_snapshots', 'pgtr_ntby_qty')
    op.drop_column('market_snapshots', 'frgn_ntby_qty')
    op.drop_column('market_snapshots', 'frgn_hldn_qty')
    op.drop_column('market_snapshots', 'hts_frgn_ehrt')
    op.drop_column('market_snapshots', 'dryy_lwpr_vrss_prpr_rate')
    op.drop_column('market_snapshots', 'dryy_lwpr_date')
    op.drop_column('market_snapshots', 'stck_dryy_lwpr')
    op.drop_column('market_snapshots', 'dryy_hgpr_vrss_prpr_rate')
    op.drop_column('market_snapshots', 'dryy_hgpr_date')
    op.drop_column('market_snapshots', 'stck_dryy_hgpr')
    op.drop_column('market_snapshots', 'd250_lwpr_vrss_prpr_rate')
    op.drop_column('market_snapshots', 'd250_lwpr_date')
    op.drop_column('market_snapshots', 'd250_lwpr')
    op.drop_column('market_snapshots', 'd250_hgpr_vrss_prpr_rate')
    op.drop_column('market_snapshots', 'd250_hgpr_date')
    op.drop_column('market_snapshots', 'd250_hgpr')
    op.drop_column('market_snapshots', 'w52_lwpr_vrss_prpr_ctrt')
    op.drop_column('market_snapshots', 'w52_lwpr_date')
    op.drop_column('market_snapshots', 'w52_lwpr')
    op.drop_column('market_snapshots', 'w52_hgpr_vrss_prpr_ctrt')
    op.drop_column('market_snapshots', 'w52_hgpr_date')
    op.drop_column('market_snapshots', 'w52_hgpr')
    op.drop_column('market_snapshots', 'stck_fcam')
    op.drop_column('market_snapshots', 'cpfn')
    op.drop_column('market_snapshots', 'hts_avls')
    op.drop_column('market_snapshots', 'lstn_stcn')
    op.drop_column('market_snapshots', 'stac_month')
    op.drop_column('market_snapshots', 'bps')
    op.drop_column('market_snapshots', 'eps')
    op.drop_column('market_snapshots', 'published_at')
    op.drop_column('market_snapshots', 'external_id')
    op.add_column('dart_disclosures', sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dart_disclosures', type_='unique')
    op.drop_index('ix_dart_disclosures_stock_code_published_at', table_name='dart_disclosures')
    op.drop_index('ix_dart_disclosures_stock_code_created_at', table_name='dart_disclosures')
    op.drop_index('ix_dart_disclosures_published_at', table_name='dart_disclosures')
    op.drop_index('ix_dart_disclosures_created_at', table_name='dart_disclosures')
    op.drop_index('ix_dart_disclosures_corp_code', table_name='dart_disclosures')
    op.alter_column('dart_disclosures', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('dart_disclosures', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('dart_disclosures', 'rcept_no',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('dart_disclosures', 'stock_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('dart_disclosures', 'stock_code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.drop_column('dart_disclosures', 'link')
    op.drop_column('dart_disclosures', 'corp_code')
    op.drop_column('dart_disclosures', 'external_id')
    op.add_column('assets', sa.Column('avg_buy_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('cash_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index('ix_assets_stock_code_updated_at', table_name='assets')
    op.drop_index('ix_assets_stock_code', table_name='assets')
    op.alter_column('assets', 'stock_code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    op.drop_column('assets', 'created_at')
    op.drop_column('assets', 'total_amount')
    op.drop_column('assets', 'unit_price')
    # ### end Alembic commands ###
